video_rental_store/video_rental_store/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace video_rental_store.Models
{
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Genre")]
        public int GenreId { get; set; }
        
        public Genre Genre { get; set; }

        [Display(Name = "Release Date")]
        public DateTime? ReleaseDate { get; set; }

        [Display(Name = "Added Date")]
        public DateTime? AddedDate { get; set; }

        [Display(Name = "Number in stack")]
        [Range(1, 20)]
        public int NumberInStock { get; set; }

        public int NumberAvailable { get; set; }


        public static readonly byte MinInStack = 1;
        public static readonly byte MaxInStack = 20;

    }
}

video_rental_store/video_rental_store/Controllers/Api/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using video_rental_store.Dtos;
using video_rental_store.Models;

namespace video_rental_store.Controllers.Api
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        public IHttpActionResult GetMovies(string query = null)
        {
            var movies = _context.Movies
                .Include(m => m.Genre)
                .Where( m => m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
                movies = movies.Where(m => m.Name.Contains(query));

            var moveisDbos = movies
                .ToList().
                Select(Mapper.Map<Movie, MovieDto>);


            return Ok(movies);  
        }

        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(p => p.Id == id);

            if (movie == null)
                return NotFound();

            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }

        [HttpPost]
        public IHttpActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;

            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDto);
        }

        [HttpPut]
        public void UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                BadRequest();

            var movieInDb = _context.Movies.SingleOrDefault(p => p.Id == id);
            if (movieInDb == null)
                NotFound();

            Mapper.Map(movieDto, movieInDb);

            _context.SaveChanges();
        }

        [HttpDelete]
        public void DeleteMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(p => p.Id == id);

            if (movie == null)
                NotFound();

            _context.Movies.Remove(movie);
            _context.SaveChanges();

        }
    }
}

video_rental_store/video_rental_store/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using video_rental_store.Migrations;
using video_rental_store.Models;
using video_rental_store.ViewModel;
using video_rental_store.ViewModels;

namespace video_rental_store.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: MovieIds
        [OutputCache(Duration = 0, VaryByParam = "*", NoStore = true)]
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.CanManageMovies))
                return View("List");

            return View("ReadOnlyList");
        }


        [OutputCache(Duration = 0, VaryByParam = "*", NoStore = true)]
        public ActionResult Details(int id)
        {
            var movies = _context.Movies.Include(m => m.Genre).FirstOrDefault(p => p.Id == id);

            if (movies == null)
                return HttpNotFound();

            return View(movies);
        }

        [Route("MovieIds/released/{year:regex(\\d{4}):int?}/{month:range(1,12):int?}")]
        public ActionResult ByReleaseDate(int? year, int? month)
        {
            if (!year.HasValue)
            {
                year = DateTime.Now.Year;
            }

            if (!month.HasValue)
            {
                month = DateTime.Now.Month;
            }

            return Content(year + " " + month);
            //return View();
        }
        public ActionResult Random()
        {
            var movie = new Movie() { Name = "Shrek"};
            var customers = new List<Customer>
            {
                new Customer {Name = "Customer 1"},
                new Customer {Name = "Customer 2"}
            };

            var viewModel = new RandomMovieViewModel
            {
                Movie = movie,
                Customers = customers
            };

            return View(viewModel);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult New()
        {
            var genres = _context.Genres.ToList();

            var viewModel = new MovieFormViewModel
            {
                Genres = genres
            };

            return View("MovieForm", viewModel);

        }

        [Route("Movies/Edit/{id}")]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult Edit(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);

            if (movie == null)
                return HttpNotFound();

            var viewModel = new MovieFormViewModel(movie)
            {
                Genres = _context.Genres.ToList()
            };

            return View("MovieForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult Save(Movie movie)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new MovieFormViewModel(movie)
                {
                    Genres = _context.Genres.ToList()
                };

                return View("MovieForm", viewModel);

            }

            if (movie.Id == 0)
            {
                movie.AddedDate = DateTime.Now;
           //     movie.NumberAvailable = movie.NumberInStock;
                _context.Movies.Add(movie);
            }
            else
            {
                var movieInDB = _context.Movies.Single(m => m.Id == movie.Id);

                movieInDB.Name = movie.Name;
                movieInDB.AddedDate = DateTime.Now;
                movieInDB.GenreId = movie.GenreId;
                movieInDB.ReleaseDate = movie.ReleaseDate;
            //    movieInDB.NumberAvailable = movieInDB.NumberAvailable + (movie.NumberInStock - movieInDB.NumberInStock);
                movieInDB.NumberInStock = movie.NumberInStock;
            }

            try
            {
                _context.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                Console.WriteLine(e);
            }

            return RedirectToAction("Index");
        }
    }
}

video_rental_store/video_rental_store/Views/Movies/Details.cshtml
@model video_rental_store.Models.Movie
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

<ul>
    <li>Genre: @Model.Genre.Name</li>
    <li>Release Date: @Model.ReleaseDate.Value.DayOfWeek, @Model.ReleaseDate.Value.Month, @Model.ReleaseDate.Value.Day, @Model.ReleaseDate.Value.Year</li>
    <li>Added Date: @Model.AddedDate.Value.DayOfWeek, @Model.AddedDate.Value.Month, @Model.AddedDate.Value.Day, @Model.AddedDate.Value.Year</li>
    <li>Number in Stack: @Model.NumberInStock</li>

</ul>

video_rental_store/video_rental_store/Views/Movies/List.cshtml
@model IEnumerable<video_rental_store.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<p>
    @Html.ActionLink("New Movie", "New", "Movies", null, new { @class = "btn btn-primary" })
</p>
<table id="movies" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Movies</th>
            <th>Genre</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
           
    </tbody>
</table>



@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#movies").DataTable({
                ajax: {
                    url: "/api/movies",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function(data, type, movie) {
                            return "<a href='/movies/edit/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name"
                    },
                    {
                        data: "id",
                        render: function(data) {
                            return "<button class='btn-link js-delete' data-movie-id=" + data + ">Delete</button>";
                        }
                    }
                ]
            });


            $("#movies").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this movie?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/movies/" + button.attr("data-movie-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });
        });
    </script>
}

video_rental_store/video_rental_store/Views/Movies/MovieForm.cshtml
@model video_rental_store.ViewModels.MovieFormViewModel
@{
    ViewBag.Title = "MovieForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (@Model.Id == null || @Model.Id == 0)
{
    <h2>New Movie</h2>
}
else
{
    <h2>Edit Movie</h2>
}


@using(@Html.BeginForm("Save","Movies"))
{
    @Html.ValidationSummary()
<div class="form-group">
    @Html.LabelFor(p => p.Name)
    @Html.TextBoxFor(p => p.Name,new { @class = "form-control"})
    @Html.ValidationMessageFor(p=>p.Name)
</div>
<div class="form-group">
    @Html.LabelFor(p => p.ReleaseDate)
    @Html.TextBoxFor(p => p.ReleaseDate, "{0:d MMM yyyy}", new { @class = "form-control"})
    @Html.ValidationMessageFor(p=>p.ReleaseDate)
</div>
<div class="form-group">
    @Html.LabelFor(p => p.NumberInStock)
    @Html.TextBoxFor(p => p.NumberInStock,new { @class = "form-control"})
    @Html.ValidationMessageFor(p=>p.NumberInStock)
</div>
    <div class="form-group">
        @Html.LabelFor(p => p.GenreId)
        @Html.DropDownListFor(p => p.GenreId, new SelectList(Model.Genres, "Id", "Name"), "Select Genre", new { @class = "form-control" })
        @Html.ValidationMessageFor(p=>p.GenreId)
</div>
    @Html.HiddenFor(p => p.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

@section scripts
{
@Scripts.Render("~/bundles/jqueryval")
}

video_rental_store/video_rental_store/Views/Movies/Random.cshtml
@model video_rental_store.ViewModel.RandomMovieViewModel

@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var className = Model.Customers.Count > 5 ? "popular" : null;
}

<h2 class = "@className">@Model.Movie.Name</h2>

@if (@Model.Customers.Count == 0 )
{
    <p>No one has rented this movie before.</p>
}
else
{
    <ul>
        @foreach (var customer in @Model.Customers)
        {
            <li>@customer.Name</li>
        }

    </ul>
}

video_rental_store/video_rental_store/Views/Movies/ReadOnlyList.cshtml
@model IEnumerable<video_rental_store.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<table id="movies" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Movies</th>
            <th>Genre</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>



@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#movies").DataTable({
                ajax: {
                    url: "/api/movies",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name"
                        
                    },
                    {
                        data: "genre.name"
                    }
                ]
            });
        });
    </script>
}